/*! Generated by redux-scfld */
import action from 'redux-base/createAction';
import {
  NAMESPACE_APP,
  APP_CHANGE_VALUE,
} from '../../types';

export default action(NAMESPACE_APP, APP_CHANGE_VALUE, (getState, diff) => {
  const { app: { value } } = getState();
  return { value: value + diff };
});
