/*! Generated by redux-scfld */
import action from 'redux-base/createAction';
import {
  NAMESPACE_APP,
  APP_LOAD,
} from '../../types';

export default action(NAMESPACE_APP, APP_LOAD, () => ({ value: 0 }));
